safe:        false
port: 4000
baseurl:    /
url: http://blog.lidaobing.com
title: "LI Daobing's Blog"
description: "LI Daobing's Blog"

destination: ./_site
plugins: [jekyll-paginate]

future:      true
lsi:         false
highlighter: rouge
markdown:    kramdown
permalink:   date
hostname: blog.lidaobing.com
paginate: 20
paginate_path: "/page:num/"
author: "LI Daobing"
author_email: "lidaobing@gmail.com"

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  syntax_highlighter: rouge
